// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AbacRule struct {
	ID            int16
	Name          string
	Description   sql.NullString
	TargetAction  string
	ConditionJson json.RawMessage
	Effect        string
	Priority      int16
	IsActive      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AbacRuleLog struct {
	ID                 uuid.UUID
	RuleID             sql.NullInt16
	UserID             uuid.UUID
	TeamID             uuid.NullUUID
	Action             string
	AttributesSnapshot json.RawMessage
	Result             string
	CreatedAt          time.Time
}

type AiGenerationLog struct {
	ID            uuid.UUID
	TeamID        uuid.UUID
	UserID        uuid.UUID
	RequirementID uuid.UUID
	Status        string
	ErrorMessage  sql.NullString
	CreatedAt     time.Time
}

type AuditLog struct {
	ID           uuid.UUID
	UserID       uuid.NullUUID
	TeamID       uuid.NullUUID
	Action       string
	ResourceType sql.NullString
	ResourceID   uuid.NullUUID
	RbacResult   string
	AbacRuleID   sql.NullInt16
	Result       string
	IpAddress    sql.NullString
	CreatedAt    time.Time
}

type Epic struct {
	ID          uuid.UUID
	RoadmapID   uuid.UUID
	Title       string
	Description sql.NullString
	PhaseNumber int16
	OrderIndex  int16
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GlobalRole struct {
	ID    int16
	Name  string
	Level int16
}

type LearningLog struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ResourceID  uuid.UUID
	Status      string
	CompletedAt sql.NullTime
	CreatedAt   time.Time
}

type LearningResource struct {
	ID         uuid.UUID
	TaskID     uuid.NullUUID
	SkillName  sql.NullString
	Title      string
	Url        string
	SourceType string
	AddedBy    uuid.NullUUID
	CreatedAt  time.Time
}

type Milestone struct {
	ID          uuid.UUID
	RoadmapID   uuid.UUID
	Title       string
	DueDate     time.Time
	IsCompleted bool
	CompletedAt sql.NullTime
	CreatedAt   time.Time
}

type Notification struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	Type                string
	Title               string
	Body                sql.NullString
	IsRead              bool
	RelatedResourceType sql.NullString
	RelatedResourceID   uuid.NullUUID
	CreatedAt           time.Time
}

type Requirement struct {
	ID              uuid.UUID
	TeamID          uuid.UUID
	ProductType     string
	DifficultyLevel int16
	FreeText        sql.NullString
	SupplementUrl   sql.NullString
	Status          string
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type RequirementFeature struct {
	ID            uuid.UUID
	RequirementID uuid.UUID
	FeatureName   string
	IsRequired    bool
}

type Roadmap struct {
	ID            uuid.UUID
	TeamID        uuid.UUID
	RequirementID uuid.UUID
	Status        string
	ConfirmedAt   sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Sprint struct {
	ID        uuid.UUID
	RoadmapID uuid.UUID
	Title     string
	StartDate time.Time
	EndDate   time.Time
	CreatedAt time.Time
}

type SprintTask struct {
	SprintID uuid.UUID
	TaskID   uuid.UUID
}

type Story struct {
	ID          uuid.UUID
	EpicID      uuid.UUID
	Title       string
	Description sql.NullString
	OrderIndex  int16
	CreatedAt   time.Time
}

type Task struct {
	ID             uuid.UUID
	StoryID        uuid.NullUUID
	RoadmapID      uuid.UUID
	Title          string
	Description    sql.NullString
	EstimatedHours sql.NullString
	Status         string
	AssignedUserID uuid.NullUUID
	DueDate        sql.NullTime
	PhaseNumber    int16
	OrderIndex     int16
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type TaskChecklist struct {
	ID         uuid.UUID
	TaskID     uuid.UUID
	Label      string
	IsChecked  bool
	OrderIndex int16
	CreatedAt  time.Time
}

type TaskComment struct {
	ID        uuid.UUID
	TaskID    uuid.UUID
	UserID    uuid.UUID
	Body      string
	ImageUrl  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TaskDependency struct {
	BlockerTaskID uuid.UUID
	BlockedTaskID uuid.UUID
}

type Team struct {
	ID                   uuid.UUID
	Name                 string
	Goal                 string
	Level                string
	StartDate            time.Time
	EndDate              time.Time
	IsArchived           bool
	InviteToken          sql.NullString
	InviteTokenExpiresAt sql.NullTime
	CreatedBy            uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type TeamRole struct {
	ID    int16
	Name  string
	Level int16
}

type TechStack struct {
	ID        uuid.UUID
	RoadmapID uuid.UUID
	Category  string
	Name      string
	Reason    sql.NullString
	IsAdopted bool
	CreatedAt time.Time
}

type UserGlobalRole struct {
	UserID       uuid.UUID
	GlobalRoleID int16
	GrantedAt    time.Time
}

type UserProfile struct {
	ID         uuid.UUID
	Name       string
	AvatarUrl  sql.NullString
	Bio        sql.NullString
	SkillLevel string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type UserSkill struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	SkillName       string
	ExperienceYears sql.NullString
	IsLearningGoal  bool
	CreatedAt       time.Time
}

type UserSkillAchievement struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	SkillName  string
	AchievedAt time.Time
}

type UserTeamRole struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	TeamID         uuid.UUID
	TeamRoleID     int16
	FunctionalRole sql.NullString
	JoinedAt       time.Time
}
