// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requirements.sql

package query

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRequirement = `-- name: CreateRequirement :one
INSERT INTO requirements (team_id, product_type, difficulty_level, free_text, supplement_url, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, team_id, product_type, difficulty_level, free_text, supplement_url, status, created_by, created_at, updated_at
`

type CreateRequirementParams struct {
	TeamID          uuid.UUID
	ProductType     string
	DifficultyLevel int16
	FreeText        sql.NullString
	SupplementUrl   sql.NullString
	CreatedBy       uuid.UUID
}

func (q *Queries) CreateRequirement(ctx context.Context, arg CreateRequirementParams) (Requirement, error) {
	row := q.db.QueryRowContext(ctx, createRequirement,
		arg.TeamID,
		arg.ProductType,
		arg.DifficultyLevel,
		arg.FreeText,
		arg.SupplementUrl,
		arg.CreatedBy,
	)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProductType,
		&i.DifficultyLevel,
		&i.FreeText,
		&i.SupplementUrl,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRequirementFeature = `-- name: CreateRequirementFeature :one
INSERT INTO requirement_features (requirement_id, feature_name)
VALUES ($1, $2)
RETURNING id, requirement_id, feature_name, is_required
`

type CreateRequirementFeatureParams struct {
	RequirementID uuid.UUID
	FeatureName   string
}

func (q *Queries) CreateRequirementFeature(ctx context.Context, arg CreateRequirementFeatureParams) (RequirementFeature, error) {
	row := q.db.QueryRowContext(ctx, createRequirementFeature, arg.RequirementID, arg.FeatureName)
	var i RequirementFeature
	err := row.Scan(
		&i.ID,
		&i.RequirementID,
		&i.FeatureName,
		&i.IsRequired,
	)
	return i, err
}

const deleteRequirementFeatures = `-- name: DeleteRequirementFeatures :exec
DELETE FROM requirement_features
WHERE requirement_id = $1
`

func (q *Queries) DeleteRequirementFeatures(ctx context.Context, requirementID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRequirementFeatures, requirementID)
	return err
}

const getRequirementByID = `-- name: GetRequirementByID :one
SELECT id, team_id, product_type, difficulty_level, free_text, supplement_url, status, created_by, created_at, updated_at FROM requirements
WHERE id = $1
`

func (q *Queries) GetRequirementByID(ctx context.Context, id uuid.UUID) (Requirement, error) {
	row := q.db.QueryRowContext(ctx, getRequirementByID, id)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProductType,
		&i.DifficultyLevel,
		&i.FreeText,
		&i.SupplementUrl,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequirementByTeamID = `-- name: GetRequirementByTeamID :one
SELECT id, team_id, product_type, difficulty_level, free_text, supplement_url, status, created_by, created_at, updated_at FROM requirements
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetRequirementByTeamID(ctx context.Context, teamID uuid.UUID) (Requirement, error) {
	row := q.db.QueryRowContext(ctx, getRequirementByTeamID, teamID)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProductType,
		&i.DifficultyLevel,
		&i.FreeText,
		&i.SupplementUrl,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRequirementFeatures = `-- name: ListRequirementFeatures :many
SELECT id, requirement_id, feature_name, is_required FROM requirement_features
WHERE requirement_id = $1
ORDER BY id
`

func (q *Queries) ListRequirementFeatures(ctx context.Context, requirementID uuid.UUID) ([]RequirementFeature, error) {
	rows, err := q.db.QueryContext(ctx, listRequirementFeatures, requirementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequirementFeature
	for rows.Next() {
		var i RequirementFeature
		if err := rows.Scan(
			&i.ID,
			&i.RequirementID,
			&i.FeatureName,
			&i.IsRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRequirement = `-- name: LockRequirement :one
UPDATE requirements
SET status     = 'locked',
    updated_at = NOW()
WHERE id = $1 AND status = 'draft'
RETURNING id, team_id, product_type, difficulty_level, free_text, supplement_url, status, created_by, created_at, updated_at
`

func (q *Queries) LockRequirement(ctx context.Context, id uuid.UUID) (Requirement, error) {
	row := q.db.QueryRowContext(ctx, lockRequirement, id)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProductType,
		&i.DifficultyLevel,
		&i.FreeText,
		&i.SupplementUrl,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRequirement = `-- name: UpdateRequirement :one
UPDATE requirements
SET product_type     = $2,
    difficulty_level = $3,
    free_text        = $4,
    supplement_url   = $5,
    updated_at       = NOW()
WHERE id = $1 AND status = 'draft'
RETURNING id, team_id, product_type, difficulty_level, free_text, supplement_url, status, created_by, created_at, updated_at
`

type UpdateRequirementParams struct {
	ID              uuid.UUID
	ProductType     string
	DifficultyLevel int16
	FreeText        sql.NullString
	SupplementUrl   sql.NullString
}

func (q *Queries) UpdateRequirement(ctx context.Context, arg UpdateRequirementParams) (Requirement, error) {
	row := q.db.QueryRowContext(ctx, updateRequirement,
		arg.ID,
		arg.ProductType,
		arg.DifficultyLevel,
		arg.FreeText,
		arg.SupplementUrl,
	)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProductType,
		&i.DifficultyLevel,
		&i.FreeText,
		&i.SupplementUrl,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
