// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roadmaps.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const hasConfirmedRoadmapForTeam = `-- name: HasConfirmedRoadmapForTeam :one
SELECT EXISTS (
    SELECT 1 FROM roadmaps
    WHERE team_id = $1 AND status = 'confirmed'
) AS exists
`

// チームに confirmed 状態のロードマップが存在するか確認する
func (q *Queries) HasConfirmedRoadmapForTeam(ctx context.Context, teamID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasConfirmedRoadmapForTeam, teamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
