// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package query

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const assignTeamOwner = `-- name: AssignTeamOwner :exec
INSERT INTO user_team_roles (user_id, team_id, team_role_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AssignTeamOwnerParams struct {
	UserID     uuid.UUID
	TeamID     uuid.UUID
	TeamRoleID int16
}

func (q *Queries) AssignTeamOwner(ctx context.Context, arg AssignTeamOwnerParams) error {
	_, err := q.db.ExecContext(ctx, assignTeamOwner, arg.UserID, arg.TeamID, arg.TeamRoleID)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, goal, level, start_date, end_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, goal, level, start_date, end_date, is_archived, invite_token, invite_token_expires_at, created_by, created_at, updated_at
`

type CreateTeamParams struct {
	Name      string
	Goal      string
	Level     string
	StartDate time.Time
	EndDate   time.Time
	CreatedBy uuid.UUID
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.Name,
		arg.Goal,
		arg.Level,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.Level,
		&i.StartDate,
		&i.EndDate,
		&i.IsArchived,
		&i.InviteToken,
		&i.InviteTokenExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, goal, level, start_date, end_date, is_archived, invite_token, invite_token_expires_at, created_by, created_at, updated_at FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.Level,
		&i.StartDate,
		&i.EndDate,
		&i.IsArchived,
		&i.InviteToken,
		&i.InviteTokenExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByInviteToken = `-- name: GetTeamByInviteToken :one
SELECT id, name, goal, level, start_date, end_date, is_archived, invite_token, invite_token_expires_at, created_by, created_at, updated_at FROM teams
WHERE invite_token = $1
`

func (q *Queries) GetTeamByInviteToken(ctx context.Context, inviteToken sql.NullString) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByInviteToken, inviteToken)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.Level,
		&i.StartDate,
		&i.EndDate,
		&i.IsArchived,
		&i.InviteToken,
		&i.InviteTokenExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTeamRoleID = `-- name: GetUserTeamRoleID :one
SELECT tr.level AS team_role_level, tr.name AS team_role_name
FROM user_team_roles utr
JOIN team_roles tr ON tr.id = utr.team_role_id
WHERE utr.user_id = $1 AND utr.team_id = $2
`

type GetUserTeamRoleIDParams struct {
	UserID uuid.UUID
	TeamID uuid.UUID
}

type GetUserTeamRoleIDRow struct {
	TeamRoleLevel int16
	TeamRoleName  string
}

func (q *Queries) GetUserTeamRoleID(ctx context.Context, arg GetUserTeamRoleIDParams) (GetUserTeamRoleIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserTeamRoleID, arg.UserID, arg.TeamID)
	var i GetUserTeamRoleIDRow
	err := row.Scan(&i.TeamRoleLevel, &i.TeamRoleName)
	return i, err
}

const isTeamMember = `-- name: IsTeamMember :one
SELECT EXISTS (
    SELECT 1 FROM user_team_roles
    WHERE user_id = $1 AND team_id = $2
) AS is_member
`

type IsTeamMemberParams struct {
	UserID uuid.UUID
	TeamID uuid.UUID
}

func (q *Queries) IsTeamMember(ctx context.Context, arg IsTeamMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTeamMember, arg.UserID, arg.TeamID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const isTeamOwner = `-- name: IsTeamOwner :one
SELECT EXISTS (
    SELECT 1 FROM user_team_roles utr
    JOIN team_roles tr ON tr.id = utr.team_role_id
    WHERE utr.user_id = $1 AND utr.team_id = $2 AND tr.level >= 20
) AS is_owner
`

type IsTeamOwnerParams struct {
	UserID uuid.UUID
	TeamID uuid.UUID
}

func (q *Queries) IsTeamOwner(ctx context.Context, arg IsTeamOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTeamOwner, arg.UserID, arg.TeamID)
	var is_owner bool
	err := row.Scan(&is_owner)
	return is_owner, err
}

const issueInviteToken = `-- name: IssueInviteToken :one
UPDATE teams
SET invite_token = $2, invite_token_expires_at = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, goal, level, start_date, end_date, is_archived, invite_token, invite_token_expires_at, created_by, created_at, updated_at
`

type IssueInviteTokenParams struct {
	ID                   uuid.UUID
	InviteToken          sql.NullString
	InviteTokenExpiresAt sql.NullTime
}

func (q *Queries) IssueInviteToken(ctx context.Context, arg IssueInviteTokenParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, issueInviteToken, arg.ID, arg.InviteToken, arg.InviteTokenExpiresAt)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.Level,
		&i.StartDate,
		&i.EndDate,
		&i.IsArchived,
		&i.InviteToken,
		&i.InviteTokenExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const joinTeamAsMember = `-- name: JoinTeamAsMember :exec
INSERT INTO user_team_roles (user_id, team_id, team_role_id)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, team_id) DO NOTHING
`

type JoinTeamAsMemberParams struct {
	UserID uuid.UUID
	TeamID uuid.UUID
}

func (q *Queries) JoinTeamAsMember(ctx context.Context, arg JoinTeamAsMemberParams) error {
	_, err := q.db.ExecContext(ctx, joinTeamAsMember, arg.UserID, arg.TeamID)
	return err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT up.id, up.name, up.avatar_url, up.skill_level,
       tr.name AS team_role_name, utr.joined_at, utr.functional_role
FROM user_team_roles utr
JOIN user_profiles up ON up.id = utr.user_id
JOIN team_roles tr ON tr.id = utr.team_role_id
WHERE utr.team_id = $1
ORDER BY utr.joined_at
`

type ListTeamMembersRow struct {
	ID             uuid.UUID
	Name           string
	AvatarUrl      sql.NullString
	SkillLevel     string
	TeamRoleName   string
	JoinedAt       time.Time
	FunctionalRole sql.NullString
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AvatarUrl,
			&i.SkillLevel,
			&i.TeamRoleName,
			&i.JoinedAt,
			&i.FunctionalRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByCreatedBy = `-- name: ListTeamsByCreatedBy :many
SELECT id, name, goal, level, start_date, end_date, is_archived, invite_token, invite_token_expires_at, created_by, created_at, updated_at FROM teams
WHERE created_by = $1
`

func (q *Queries) ListTeamsByCreatedBy(ctx context.Context, createdBy uuid.UUID) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsByCreatedBy, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Goal,
			&i.Level,
			&i.StartDate,
			&i.EndDate,
			&i.IsArchived,
			&i.InviteToken,
			&i.InviteTokenExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByMember = `-- name: ListTeamsByMember :many
SELECT t.id, t.name, t.goal, t.level, t.start_date, t.end_date, t.is_archived,
       t.invite_token, t.invite_token_expires_at, t.created_by, t.created_at, t.updated_at
FROM teams t
JOIN user_team_roles utr ON utr.team_id = t.id
WHERE utr.user_id = $1
ORDER BY t.created_at DESC
`

func (q *Queries) ListTeamsByMember(ctx context.Context, userID uuid.UUID) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Goal,
			&i.Level,
			&i.StartDate,
			&i.EndDate,
			&i.IsArchived,
			&i.InviteToken,
			&i.InviteTokenExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, goal, level, start_date, end_date, is_archived, invite_token, invite_token_expires_at, created_by, created_at, updated_at
`

type UpdateTeamParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, updateTeam, arg.ID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.Level,
		&i.StartDate,
		&i.EndDate,
		&i.IsArchived,
		&i.InviteToken,
		&i.InviteTokenExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
